### PR TITLE
SDK v2.2.2

### PR DESCRIPTION
**Pull request by jonathanlurie**

### CODE REVIEW

**Comment by petrsloup** [comment]
Well, you only updated the `latest` but did not add `v2.2.2` ? (Also, we are missing `v2.2.1` as well for some reason..)

**Comment by jonathanlurie** [comment]
Oh indeed!

**Comment by jonathanlurie** [comment]
The thing is that there was an error un v2.2.1, even though it was just affecting the TS/ES bundle, i felt like maybe it's better not to push it

**Comment by petrsloup** [comment]
Looking at the CDN logs, most requested `maptiles-sdk-js` files over the last 30 days:
image

So, we definitely don't want to remove the `.umd.min.js` since it would break a lot of stuff.
We could just copy the non-min version? Or maybe it's time to finally stop updating the `latest` (since we changed the bundling) and just add new versions instead..

**Comment by jonathanlurie** [comment]
true, i renamed the files with the min suffix, because they are actually minified source

**Comment by petrsloup** [comment]
Well, looking at the screenshot, we also need the `.umd.js` anyway (and probably other files as well, just to be safe?).. so maybe duplicating the `.umd.min.js`?

**Comment by jonathanlurie** [comment]
The Vite config (used to be Rollup) is no longer generating both min and non-min UMDs. Now, min is generated in prod mode and non-min in dev mode, but the latter I run only locally. I just added dupes under a non-min name. I no longer push the ES bundle on CDN, nor the TS type file, since those are never used from CDN.

**Review by petrsloup — APPROVED** [review]

**Pull request merged**
