### PR TITLE
Leaflet maptiler plugin v2

### PR DESCRIPTION
**Pull request by jonathanlurie**
[RD-184](https://maptiler.atlassian.net/browse/RD-184)

This PR contains the NPM-friendly update of the Leaflet MapTiler SDK plugin (aka. Leaflet Vector Tile plugin)

[RD-184]: https://maptiler.atlassian.net/browse/RD-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jonathanlurie** [comment]
The file naming has changed since v2 of this plugin. The file "leaflet-maptilersdk.js" used to be the UMD bundle, but now this file contains the ES module. In addition, there is the file "leaflet-maptilersdk.umd.js", which is the UMD.

**Review by petrsloup — CHANGES_REQUESTED** [review]
We discussed that we can upgrade the `latest` since v2 should be compatible with v1, but doing it like this would break all the applications currently using `latest`, wouldn't it?

I see two options here:
- Stop using `latest` -- freeze it at v1 and don't upgrade. However, there seems to be more traffic to the `latest` than `v1.0.0` 😞 People would have to explicitly migrate to `v2.0.0`...
- Keep the previous naming (`.js` is umd) and introduce something like `.es.js` instead ? But this is not aligned with how we handle other libraries 🤷

**Comment by petrsloup** [comment]
Third option:
- Load es modules from CDN probably does not make sense. Just use umd on CDN and keep the naming as it used to be.

**Comment by jonathanlurie** [comment]
Renaming `leaflet-maptilersdk.umd.js` to `leaflet-maptilersdk.js` so that it's backward compatible

**Review by petrsloup — APPROVED** [review]
👍

**Pull request merged**
